### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by whosthatperson** [TheF1xer/GateClient#4]
**What feature would you like to be added.**
Make it so you can move the gui around, as in the modules so you can customize it how you like
Add Crystal Aura and a hud/gui editor 

**Is your feature request related to a problem? Please describe.**
Nope, just a suggestion for personal preference 

**Additional context**
Your client is amazing and has so much potential

**Comment by TheF1xer** [comment]
I never really understood why GUI elements are always movable in most clients so I didn't really added that. I will probably do it though eventually, but could you tell my why it is so popular?

I'm really bad at CPvP and I mean really bad, so I don't think I understand it enough to make a CA module worth using. Since I don't really understand how crystal placements should be done, I plan to code one eventually but I think I would need help from people that can CPvP better than me xd.

Also, I'm already planning on doing a HUD editor but I will probably require a small rework of my current HUD system so it might take a little while, but I really want to add a HUD editor to my client.

**Comment by pancracium** [comment]
My gui is bugged the half of It is out of the screen

**Comment by TheF1xer** [comment]
> My gui is bugged the half of It is out of the screen

First, create a new issue for unrelated stuff. Second, you must change your GUI Scale to Normal in the Minecraft Settings
